### PR TITLE
task done by aditya

### PR DESCRIPTION
**Pull request by adityacyan**
The pr has my task contribution done , I have added an index file , a js file and a css file for the task , i have not use css tailwind but rest assured i would as i m learning it right now, i have attached video of my task for further information.

https://github.com/dev04sa/Team405_Tasks/assets/150646380/53293e09-3ae4-480c-9ae6-e2c7bcc7ecef

image

### CODE REVIEW

**Comment by dev04sa** [comment]
@adityacyan , Great work!!.
just try to pull the changes from main repo and delete the .idea folder , there is no need to that folder here.

**Comment by adityacyan** [comment]
> @adityacyan , Great work!!. just try to pull the changes from main repo and delete the .idea folder , there is no need to that folder here.

i have done same

**Comment by dev04sa** [comment]
@adityacyan , pull the changes from repo.
then we good to merge 🚀 .

**Comment by adityacyan** [comment]
> @adityacyan , pull the changes from repo.
> then we good to merge 🚀 .

You mean i sync my fork?

**Comment by adityacyan** [comment]
check now it should be okay:

**Comment by dev04sa** [comment]
@adityacyan , Great work!!.
now it's working fine.

**Pull request merged**
