### PR TITLE
ToDo by anshu jha 

### PR DESCRIPTION
**Pull request by anshukantjha**
In this i have contributed for todo list making but actual goal was to learn how to contribute and do the basics of javascript

### CODE REVIEW

**Comment by dev04sa** [comment]
@anshukantjha , you have create a folder with name and inside that folder your code is need to  be there not inside dev folder .
try to correct this one . and make sure while creating pull request you should provide the screenshots relevant to your task.

**Comment by dev04sa** [comment]
@anshukantjha , great work!!. your code is working fine . just do the requested changes.

**Comment by dev04sa** [comment]
@anshukantjha you just need to add name directory , don't delete any existing directory.

**Comment by anshukantjha** [comment]
Actually I have done the same , commit message was given deleted file as my git status  was showing deleted dev/index.html and all 
can you please take a look once more

**Comment by dev04sa** [comment]
@anshukantjha still showing the same.
kindly pull the changes using `git pull` then commit .

**Comment by dev04sa** [comment]
@anshukantjha  , In your PR there is issue : -
already existing folders are not present in your PR . only your folder is showing . if I merge your PR then , PR's of rest members get deleted.
Screenshot 2024-05-24 155151
this one is correct : -
Screenshot 2024-05-24 155136

**Comment by dev04sa** [comment]
Don't be in hurry , take your time and resolved it.

**Comment by anshukantjha** [comment]
what should i do - close the PR and make another fork do the same ??

**Comment by dev04sa** [comment]
now everything is fine , just Dev folder is missing . kindly add that too.

**Pull request closed without merging**
