### PR TITLE
Akshat todolist

### PR DESCRIPTION
**Pull request by AkshatKumar1609**

### CODE REVIEW

**Comment by dev04sa** [comment]
@AkshatKumar1609 , Great work!!.
just pull the existing changes. then we good to merge.

**Comment by dev04sa** [comment]
and make sure while creating PR , provide the necessary screenshots.

**Review by AkshatKumar1609 — COMMENTED** [review]
Screenshot 2024-05-24 125213
Screenshot 2024-05-24 125405

**Comment by dev04sa** [comment]
@AkshatKumar1609 , pull the changes again  beacuse one more PR is merged.

**Pull request merged**
