### PR TITLE
Completed Team405_Task:Suryansh Verma

### PR DESCRIPTION
**Pull request by suryanshvermaa**

### CODE REVIEW

**Comment by dev04sa** [comment]
@suryanshvermaa , make sure this should be responsive.
do the necessary changes.

**Comment by dev04sa** [comment]
@suryanshvermaa , make sure this should be responsive.
do the necessary changes.

**Comment by suryanshvermaa** [comment]
Screenshot 2024-05-20 172320
Screenshot 2024-05-20 172336
Screenshot 2024-05-20 172348


added responsiveness for all devices

**Review by dev04sa — APPROVED** [review]
@suryanshvermaa , Great work.
now is working fine.

**Pull request merged**
